### ISSUE TITLE
Unable to persist database

### ISSUE THREAD

**Issue by KeironO** [ironsmile/euterpe#30]
Regardless of whatever I try to do, I am unable to persist the database when installed via docker.

docker-compose.yml:

```
version: '3.3'
services:
    euterpe:
        volumes:
            - '/home/keo7/services/euterpe/data:/root/.euterpe'
            - '/home/keo7/consti/Music/:/root/Music'
        ports:
            - '9996:9996'
        image: 'ironsmile/euterpe:latest'

```
