### ISSUE TITLE
Error generating JWT: jwt.(Signer).Sign: HMAC key is empty.

### ISSUE THREAD

**Issue by BH1SCW** [ironsmile/euterpe#39]
hi After  sign in the page return:

`Error generating JWT: jwt.(Signer).Sign: HMAC key is empty.`

my docker-compose.yml:

```
version: '3'
services:
    kavita:
        image: ironsmile/euterpe:latest
        container_name: euterpe
        volumes:
            - /data/euterpe/config:/root/.euterpe
            - /data/euterpe/Music:/root/Music
        ports:
            - "4000:9996"
        restart: unless-stopped
```

config.json : 

```
{
    "listen": ":9996",
    "ssl": false,
    "ssl_certificate": {
        "crt": "/full/path/to/certificate/file.crt",
        "key": "/full/path/to/key/file.key"
    },
    "basic_authenticate": true,
    "authentication": {
        "user": "kong",
        "password": "xxxxxxxxxxxxxxxxxxxxxx"
    },
    "libraries": [
        "/root/Music"
    ],
    "library_scan": {
        "initial_wait_duration": "1s",
        "files_per_operation": 1500,
        "sleep_after_operation": "15ms"
    },
    "download_artwork": true,
    "discogs_auth_token": "xxxxxxxxxxxxxxxxxxxxxxx"
}
```

Thanks
